# Generated by Django 3.2.5 on 2022-03-03 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSocials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=80)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('slack', models.URLField(blank=True, null=True)),
                ('stack_overflow', models.URLField(blank=True, null=True)),
                ('add', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rphusers.addsocials')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('default_id', models.UUIDField(default=uuid.uuid1)),
                ('first_name', models.CharField(default='firstname {default_id}', max_length=100)),
                ('last_name', models.CharField(default='lastname', max_length=100)),
                ('username', models.CharField(default='user', max_length=100)),
                ('profile_picture', models.ImageField(default='', upload_to='')),
                ('bio', models.TextField(blank=True, default=True)),
                ('description', models.TextField(blank=True, default=True)),
                ('email', models.EmailField(default='useremail', max_length=254)),
                ('stamp', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('social_links', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rphusers.socials')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
