# Generated by Django 3.2.5 on 2022-03-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rphusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsocials',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addsocials',
            name='name',
            field=models.CharField(default=True, max_length=80, null=True),
        ),
    ]
