# Generated by Django 3.2.5 on 2022-03-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rphusers', '0002_auto_20220303_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsocials',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
