# Generated by Django 3.2.5 on 2022-03-03 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rphusers', '0003_alter_addsocials_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='social_links',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rphusers.socials'),
        ),
    ]
